<script lang="ts">
import type { RelationshipHint } from '~/components/RelationshipBuilder.vue'

// every kind is optional: no upload -> the AI generates it from the Bible's
// visual_dna; an upload becomes the asset's master reference image.
// A box may also stay picture-less (hint-only): its name + role still steer
// the story via StoryInput.reference_images / relationship_hints.
export type RefKind = 'character' | 'location' | 'object'
export type RefView = 'front' | 'side' | 'back' | 'pose' | 'expression'

export type RefMode = 'world' | 'exact'

export interface RefAsset {
  kind: RefKind
  name: string
  view: RefView // characters only; "front" = master identity image
  mode: RefMode // locations only; world = varied scenes in one universe
  role: string // characters only; optional story role (villain, minion…)
  is_character_sheet: boolean // characters only; upload already contains turnaround views
  file: File | null
  preview: string // object URL — the one picture shown in the box
}

// optional story role for a character reference box; '' = let the AI decide
export const CHARACTER_ROLE_OPTIONS: { value: string; label: string }[] = [
  { value: '', label: 'Role — auto (AI decides)' },
  { value: 'protagonist', label: '🌟 Protagonist / hero' },
  { value: 'deuteragonist', label: '✨ Deuteragonist' },
  { value: 'villain', label: '😈 Villain' },
  { value: 'villain_lieutenant', label: '🗡️ Child villain / lieutenant' },
  { value: 'minion', label: '🪓 Minion' },
  { value: 'mentor', label: '🧙 Mentor' },
  { value: 'ally', label: '🤝 Ally' },
  { value: 'love_interest', label: '❤️ Love interest' },
  { value: 'supporting', label: '👤 Supporting' },
]
</script>

<script setup lang="ts">
const assets = defineModel<RefAsset[]>({ default: () => [] })
const props = defineProps<{ hints?: RelationshipHint[] }>()
const emit = defineEmits<{ error: [msg: string]; link: [hint: RelationshipHint] }>()

const kindMeta: Record<RefKind, { icon: string; label: string; placeholder: string }> = {
  character: { icon: '🧑', label: 'Character', placeholder: 'Character name — e.g. KAIRA' },
  location: { icon: '🏞️', label: 'Location', placeholder: 'Location name — e.g. Dead City' },
  object: { icon: '🗡️', label: 'Object', placeholder: 'Object name — e.g. Plasma Blade' },
}

// one front image is enough — missing views (side/back/pose/expression) are
// auto-generated by the pipeline so the AI understands the full body.
// The selector exists for users who want to supply their own extra views.
const views: { value: RefView; label: string }[] = [
  { value: 'front', label: 'Front — master identity (1 រូបគ្រប់គ្រាន់)' },
  { value: 'side', label: 'Side profile' },
  { value: 'back', label: 'Back' },
  { value: 'pose', label: 'Action pose' },
  { value: 'expression', label: 'Expression close-up' },
]

// location behaviour: world (default) = photo defines the world aesthetic,
// every scene there is a different spot in the same universe; exact = the
// photo is the fixed spot shown in every scene (e.g. your own shop)
const modes: { value: RefMode; label: string }[] = [
  { value: 'world', label: '🌍 World style — scene ផ្សេងគ្នា ក្នុងពិភពតែមួយ' },
  { value: 'exact', label: '📍 Exact place — កន្លែងដដែលគ្រប់ scene' },
]

function add(kind: RefKind) {
  assets.value = [...assets.value, {
    kind,
    name: '',
    view: 'front',
    mode: 'world',
    role: '',
    is_character_sheet: false,
    file: null,
    preview: '',
  }]
}

const sheetKeywords = [
  'character sheet',
  'character_sheet',
  'turnaround',
  'refsheet',
  'model sheet',
  'model_sheet',
  'reference sheet',
  'reference_sheet',
  'multi-view',
  'multiview',
]

function remove(i: number) {
  const a = assets.value[i]
  if (a?.preview) URL.revokeObjectURL(a.preview)
  assets.value = assets.value.filter((_, j) => j !== i)
  if (linking.value === i) linking.value = null
}

function pick(i: number, e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = ''
  if (!file) return
  if (file.size > 10 * 1024 * 1024) {
    emit('error', 'Reference image exceeds 10 MB')
    return
  }
  const a = assets.value[i]
  if (!a) return
  if (a.preview) URL.revokeObjectURL(a.preview)
  a.file = file
  a.preview = URL.createObjectURL(file)
  const fileName = file.name.toLowerCase()
  if (a.kind === 'character' && sheetKeywords.some(k => fileName.includes(k))) {
    a.view = 'front'
    a.is_character_sheet = true
  }
}

onBeforeUnmount(() => assets.value.forEach(a => a.preview && URL.revokeObjectURL(a.preview)))

// ---- click-to-link: 🔗 on a box, then click another box to draw the line
const linking = ref<number | null>(null)

// link-flow feedback shown right next to the boxes (the page-level error
// banner sits at the bottom of the form where users don't see it)
const note = ref<{ text: string; tone: 'error' | 'ok' } | null>(null)
let noteTimer: ReturnType<typeof setTimeout> | null = null
function showNote(text: string, tone: 'error' | 'ok' = 'error') {
  note.value = { text, tone }
  if (noteTimer) clearTimeout(noteTimer)
  noteTimer = setTimeout(() => (note.value = null), 6000)
}

function focusName(i: number) {
  nextTick(() => boxEls[i]?.querySelector('input')?.focus())
}

function toggleLink(i: number) {
  const a = assets.value[i]
  if (!a?.name.trim()) {
    showNote('⚠ Type a name in this box first (e.g. VEX) — lines connect by name · ដាក់ឈ្មោះ box សិន បានចុច 🔗 បាន')
    focusName(i)
    return
  }
  if (a.kind === 'location') {
    showNote('⚠ Locations can\'t be linked — only characters and objects.')
    return
  }
  linking.value = linking.value === i ? null : i
}

function completeLink(i: number) {
  if (linking.value === null || linking.value === i) return
  const s = assets.value[linking.value]
  const t = assets.value[i]
  if (!s || !t) return
  if (!t.name.trim()) {
    showNote('⚠ Type a name in this box first (e.g. GRUB) — lines connect by name · ដាក់ឈ្មោះ box សិន')
    focusName(i)
    return
  }
  if (t.kind === 'location') {
    showNote('⚠ Locations can\'t be linked — only characters and objects.')
    return
  }
  // objects only take character→object edges; auto-flip if clicked backwards
  let source = s.name.trim()
  let target = t.name.trim()
  let type = 'ally_of'
  if (t.kind === 'object' && s.kind !== 'object') type = 'uses'
  else if (s.kind === 'object' && t.kind !== 'object') { [source, target] = [target, source]; type = 'uses' }
  else if (s.kind === 'object' && t.kind === 'object') {
    showNote('⚠ Objects can\'t link to each other — connect them to a character.')
    return
  }
  linking.value = null
  showNote(`✓ Linked ${source} → ${target} — change the type in the Relationships list below`, 'ok')
  emit('link', { source, target, type, label: '' })
}

// ---- SVG overlay: draw the user's relationship lines between the boxes
const EDGE_STYLE: Record<string, { color: string; label: string; directed: boolean; dashed?: boolean }> = {
  enemy_of: { color: '#ef4444', label: 'enemy of', directed: false },
  ally_of: { color: '#34d399', label: 'ally of', directed: false },
  sibling_of: { color: '#a78bfa', label: 'sibling of', directed: false },
  parent_of: { color: '#a78bfa', label: 'parent of', directed: true },
  commands: { color: '#fb923c', label: 'commands', directed: true },
  mentors: { color: '#38bdf8', label: 'mentors', directed: true },
  loves: { color: '#f472b6', label: 'loves', directed: true },
  owns: { color: '#71717a', label: 'owns', directed: true, dashed: true },
  uses: { color: '#71717a', label: 'uses', directed: true, dashed: true },
}

const gridEl = ref<HTMLElement | null>(null)
const boxEls: Record<number, HTMLElement | null> = {}
function setBoxEl(i: number, el: unknown) {
  boxEls[i] = (el as HTMLElement | null)
}

interface BoxRect { cx: number; cy: number; w: number; h: number }
const rects = ref<Record<number, BoxRect>>({})
const gridSize = ref({ w: 0, h: 0 })

function measure() {
  const g = gridEl.value
  if (!g) return
  const gr = g.getBoundingClientRect()
  gridSize.value = { w: gr.width, h: gr.height }
  const out: Record<number, BoxRect> = {}
  assets.value.forEach((_, i) => {
    const el = boxEls[i]
    if (!el || !el.isConnected) return
    const r = el.getBoundingClientRect()
    out[i] = { cx: r.left - gr.left + r.width / 2, cy: r.top - gr.top + r.height / 2, w: r.width, h: r.height }
  })
  rects.value = out
}

let ro: ResizeObserver | null = null
onMounted(() => {
  nextTick(measure)
  ro = new ResizeObserver(() => measure())
  if (gridEl.value) ro.observe(gridEl.value)
})
onBeforeUnmount(() => ro?.disconnect())
watch(
  [() => assets.value.map(a => `${a.kind}|${a.name}|${a.preview ? 1 : 0}`).join(';'), () => props.hints],
  () => nextTick(measure),
  { deep: true },
)

// hint name -> box index (same trimmed, case-insensitive match)
function boxIndexByName(name: string): number {
  const n = name.trim().toLowerCase()
  if (!n) return -1
  return assets.value.findIndex(a => a.name.trim().toLowerCase() === n)
}

interface OverlayEdge {
  key: string
  path: string
  color: string
  label: string
  labelX: number
  labelY: number
  dashed: boolean
  directed: boolean
}

const edges = computed<OverlayEdge[]>(() => {
  const hints = (props.hints ?? []).filter(h => h.source && h.target)
  const pairCount = new Map<string, number>()
  const out: OverlayEdge[] = []
  hints.forEach((h, idx) => {
    const si = boxIndexByName(h.source)
    const ti = boxIndexByName(h.target)
    if (si < 0 || ti < 0 || si === ti) return
    const s = rects.value[si]
    const t = rects.value[ti]
    if (!s || !t) return
    const style = EDGE_STYLE[h.type] ?? EDGE_STYLE.ally_of!

    const pairKey = [si, ti].sort().join('|')
    const pi = pairCount.get(pairKey) ?? 0
    pairCount.set(pairKey, pi + 1)

    const dx = t.cx - s.cx
    const dy = t.cy - s.cy
    const len = Math.hypot(dx, dy) || 1
    const nx = -dy / len
    const ny = dx / len
    const curv = [22, -46, 70, -94][pi % 4]!
    const ctrlX = (s.cx + t.cx) / 2 + nx * curv
    const ctrlY = (s.cy + t.cy) / 2 + ny * curv

    const anchor = (b: BoxRect, tx: number, ty: number) => {
      const adx = tx - b.cx
      const ady = ty - b.cy
      const scale = 1 / Math.max(Math.abs(adx) / (b.w / 2 + 5), Math.abs(ady) / (b.h / 2 + 5), 1e-6)
      return { x: b.cx + adx * Math.min(scale, 1), y: b.cy + ady * Math.min(scale, 1) }
    }
    const p0 = anchor(s, ctrlX, ctrlY)
    const p1 = anchor(t, ctrlX, ctrlY)

    out.push({
      key: `${h.source}-${h.type}-${h.target}-${idx}`,
      path: `M ${p0.x} ${p0.y} Q ${ctrlX} ${ctrlY} ${p1.x} ${p1.y}`,
      color: style.color,
      label: style.label,
      labelX: 0.25 * p0.x + 0.5 * ctrlX + 0.25 * p1.x,
      labelY: 0.25 * p0.y + 0.5 * ctrlY + 0.25 * p1.y,
      dashed: style.dashed ?? false,
      directed: style.directed,
    })
  })
  return out
})

const arrowColors = computed(() => [...new Set(edges.value.filter(e => e.directed).map(e => e.color))])
</script>

<template>
  <div>
    <div class="flex flex-wrap gap-2">
      <button
        v-for="(m, k) in kindMeta"
        :key="k"
        type="button"
        class="rounded-lg border border-zinc-700 px-3 py-1.5 text-sm hover:border-amber-400 hover:text-amber-300"
        @click="add(k as RefKind)"
      >
        + {{ m.icon }} {{ m.label }}
      </button>
    </div>

    <p v-if="linking !== null" class="mt-3 rounded-lg border border-amber-400/40 bg-amber-400/5 px-3 py-2 text-xs text-amber-200">
      🔗 Linking <b>{{ assets[linking]?.name }}</b> — click another box to connect it (or 🔗 again to cancel).
    </p>

    <p
      v-if="note"
      class="mt-3 rounded-lg border px-3 py-2 text-xs"
      :class="note.tone === 'error'
        ? 'border-red-500/50 bg-red-500/10 text-red-300'
        : 'border-emerald-500/40 bg-emerald-500/5 text-emerald-300'"
    >
      {{ note.text }}
    </p>

    <div v-if="assets.length" ref="gridEl" class="relative mt-4">
      <div class="grid grid-cols-2 gap-4 sm:grid-cols-3">
        <div
          v-for="(a, i) in assets"
          :key="i"
          :ref="el => setBoxEl(i, el)"
          class="relative rounded-xl border bg-zinc-900 p-3 transition"
          :class="[
            linking === i ? 'border-amber-400 ring-1 ring-amber-400' : 'border-zinc-700',
            linking !== null && linking !== i ? 'cursor-crosshair hover:border-amber-400/70' : '',
          ]"
          @click="linking !== null && linking !== i ? completeLink(i) : undefined"
        >
          <span class="absolute left-2 top-2 z-10 rounded-md bg-zinc-950/80 px-2 py-0.5 text-xs">
            {{ kindMeta[a.kind].icon }} {{ kindMeta[a.kind].label }}
          </span>
          <div class="absolute right-2 top-2 z-10 flex gap-1">
            <button
              v-if="a.kind !== 'location'"
              type="button"
              aria-label="Link to another box"
              class="rounded-md bg-zinc-950/80 px-2 py-0.5 text-xs"
              :class="linking === i ? 'text-amber-300' : 'text-zinc-400 hover:text-amber-300'"
              @click.stop="toggleLink(i)"
            >
              🔗
            </button>
            <button
              type="button"
              aria-label="Remove reference"
              class="rounded-md bg-zinc-950/80 px-2 py-0.5 text-xs text-red-400 hover:text-red-300"
              @click.stop="remove(i)"
            >
              ✕
            </button>
          </div>

          <label class="block cursor-pointer">
            <img v-if="a.preview" :src="a.preview" class="aspect-video w-full rounded-lg object-cover" alt="">
            <div
              v-else
              class="flex aspect-video w-full items-center justify-center rounded-lg border-2 border-dashed border-zinc-700 text-center text-xs text-zinc-500 hover:border-amber-400 hover:text-amber-300"
            >
              🖼️ Add picture — optional<br>(no photo = AI designs it)
            </div>
            <input type="file" accept="image/png,image/jpeg" class="hidden" @change="pick(i, $event)">
          </label>

          <input
            v-model.trim="a.name"
            :placeholder="kindMeta[a.kind].placeholder"
            class="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-1.5 text-sm placeholder:text-zinc-600 focus:border-amber-400 focus:outline-none"
            @click.stop
          >

          <select
            v-if="a.kind === 'character'"
            v-model="a.role"
            class="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-1.5 text-xs"
            :class="a.role ? 'text-amber-300' : 'text-zinc-400'"
            @click.stop
          >
            <option v-for="r in CHARACTER_ROLE_OPTIONS" :key="r.value" :value="r.value">{{ r.label }}</option>
          </select>

          <select
            v-if="a.kind === 'character'"
            v-model="a.view"
            class="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-1.5 text-xs text-zinc-400"
            @click.stop
          >
            <option v-for="v in views" :key="v.value" :value="v.value">{{ v.label }}</option>
          </select>

          <label
            v-if="a.kind === 'character' && a.file"
            class="mt-2 flex items-start gap-2 rounded-lg border border-zinc-800 bg-zinc-950 px-2 py-2 text-xs text-zinc-300"
            @click.stop
          >
            <input v-model="a.is_character_sheet" type="checkbox" class="mt-0.5 accent-amber-400">
            <span>
              Full character sheet / turnaround
              <span class="block text-zinc-500">
                Use this exact sheet; do not generate replacement side/back refs.
              </span>
            </span>
          </label>

          <select
            v-if="a.kind === 'location'"
            v-model="a.mode"
            class="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-1.5 text-xs text-zinc-400"
            @click.stop
          >
            <option v-for="m in modes" :key="m.value" :value="m.value">{{ m.label }}</option>
          </select>
        </div>
      </div>

      <!-- relationship lines drawn over the boxes (display only, clicks pass through) -->
      <svg
        v-if="edges.length && gridSize.w"
        class="pointer-events-none absolute inset-0 z-20"
        :width="gridSize.w"
        :height="gridSize.h"
        :viewBox="`0 0 ${gridSize.w} ${gridSize.h}`"
      >
        <defs>
          <marker
            v-for="color in arrowColors"
            :id="`ref-arrow-${color.slice(1)}`"
            :key="color"
            markerWidth="8"
            markerHeight="8"
            refX="7"
            refY="4"
            orient="auto"
            markerUnits="userSpaceOnUse"
          >
            <path d="M 0 0.5 L 8 4 L 0 7.5 Z" :fill="color" />
          </marker>
        </defs>
        <g v-for="e in edges" :key="e.key">
          <path
            :d="e.path"
            fill="none"
            :stroke="e.color"
            stroke-width="2"
            :stroke-dasharray="e.dashed ? '6 4' : undefined"
            :marker-end="e.directed ? `url(#ref-arrow-${e.color.slice(1)})` : undefined"
          />
          <rect
            :x="e.labelX - (e.label.length * 5.4 + 12) / 2"
            :y="e.labelY - 9"
            :width="e.label.length * 5.4 + 12"
            height="18"
            rx="9"
            fill="#09090b"
            :stroke="e.color"
            stroke-opacity="0.45"
          />
          <text :x="e.labelX" :y="e.labelY + 3.5" text-anchor="middle" font-size="9.5" fill="#d4d4d8">
            {{ e.label }}
          </text>
        </g>
      </svg>
    </div>
  </div>
</template>
